// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2MbWM-_KQzi9fD1QxT0_bp3tovB9-gSg',
    appId: '1:902314237344:web:779e186bffb8f1553158c5',
    messagingSenderId: '902314237344',
    projectId: 'gp11-1b161',
    authDomain: 'gp11-1b161.firebaseapp.com',
    storageBucket: 'gp11-1b161.appspot.com',
    measurementId: 'G-F0J1TVX4M4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsQecrDmpiUMG5P3jw_j9D4lTelB1js24',
    appId: '1:902314237344:android:74f4f17862e26d7e3158c5',
    messagingSenderId: '902314237344',
    projectId: 'gp11-1b161',
    storageBucket: 'gp11-1b161.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXbWlkKphSwJPI19kXeWNpU7LkwxloSn8',
    appId: '1:902314237344:ios:22e7d7cdffe844243158c5',
    messagingSenderId: '902314237344',
    projectId: 'gp11-1b161',
    storageBucket: 'gp11-1b161.appspot.com',
    iosClientId:
        '902314237344-ejf1447s381t7s2mjmu3mgfr6i5518hs.apps.googleusercontent.com',
    iosBundleId: 'com.example.gp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXbWlkKphSwJPI19kXeWNpU7LkwxloSn8',
    appId: '1:902314237344:ios:22e7d7cdffe844243158c5',
    messagingSenderId: '902314237344',
    projectId: 'gp11-1b161',
    storageBucket: 'gp11-1b161.appspot.com',
    iosClientId:
        '902314237344-ejf1447s381t7s2mjmu3mgfr6i5518hs.apps.googleusercontent.com',
    iosBundleId: 'com.example.gp',
  );
}
